### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by nojaf** [brandly/tetris-react#2]
What is the licensing for this project?
Is it ok to use in other (commercial?) projects?

**Comment by brandly** [comment]
have at it!

**Comment by nojaf** [comment]
Thanks mate

**Comment by pandaiolo** [comment]
Just a note, not sure if you already looked into it @nojaf , if you plan any for-profit use of a Tetris game : it seems that "The Tetris Company" is VERY strict on who they let use the Tetris game commercially (in the sense of not suing them / sending C&D letters / pulling apps off stores)

**Comment by nojaf** [comment]
Yes I noticed, I'll have to do my homework how to ship it. The idea is to use it in a Cordova application and create a mobile app. I'll have to inform how to proceed.

**Comment by brandly** [comment]
good point, @pandaiolo! thanks
